config/routes.rb
ESPPep::Application.routes.draw do

  resources :cards, path: "/", only: [ :new, :create, :show ]
  devise_for :users, path: "/admin"

  scope :admin do
    resources :cards, except: [ :new, :create, :show ]
    resources :clubs
    resources :users
    resources :employees, except: [ :new ]
  end

  root to: 'cards#new'

  

end

app/models/club.rb
class Club < ActiveRecord::Base
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render action: 'show', status: :created, location: @club }
      else
        format.html { render action: 'new' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name, :short)
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_form.html.haml
= form_for @club do |f|
  - if @club.errors.any?
    #error_explanation
      %h2= "#{pluralize(@club.errors.count, "error")} prohibited this club from being saved:"
      %ul
        - @club.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :short
    = f.text_field :short
  .actions
    = f.submit 'Save'

app/views/clubs/edit.html.haml
%h1 Editing club

= render 'form'

= link_to 'Show', @club
\|
= link_to 'Back', clubs_path

app/views/clubs/index.html.haml
%h1 Listing clubs

%table
  %tr
    %th Name
    %th Short
    %th
    %th
    %th

  - @clubs.each do |club|
    %tr
      %td= club.name
      %td= club.short
      %td= link_to 'Show', club
      %td= link_to 'Edit', edit_club_path(club)
      %td= link_to 'Destroy', club, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Club', new_club_path

app/views/clubs/new.html.haml
%h1 New club

= render 'form'

= link_to 'Back', clubs_path

app/views/clubs/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @club.name
%p
  %b Short:
  = @club.short

= link_to 'Edit', edit_club_path(@club)
\|
= link_to 'Back', clubs_path