config/routes.rb
ESPPep::Application.routes.draw do

  resources :cards, path: "/", only: [ :new, :create, :show ]
  devise_for :users, path: "/admin"

  scope :admin do
    resources :cards, except: [ :new, :create, :show ]
    resources :clubs
    resources :users
    resources :employees, except: [ :new ]
  end

  root to: 'cards#new'

  

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :cards, ->(employee) { where name: employee.name }
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.where(active: params[:inactive].nil?).order('name ASC')
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @employee }
      else
        format.html { render action: 'new' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :active)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.haml
= form_for @employee do |f|
  = render(partial: "shared/errors", locals: { object: @employee }) if @employee.errors.any?

  %label
    %strong= t :first_name
    = f.text_field :first_name
  %label
    %strong= t :last_name
    = f.text_field :last_name
  %label
    %strong= t :active
    = f.check_box :active
  .actions
    = f.submit 'Save'

app/views/employees/edit.html.haml
%h1 Editing employee

= render 'form'

= link_to 'Show', @employee
\|
= link_to 'Back', employees_path

app/views/employees/index.html.haml
- content_for :title, t("listing_employees")

- if @employees.empty?
  %section#employees.empty= t 'none', model: Employee.model_name.human.pluralize
- else
  %section#employees.table
    %header
      %div= t Employee.human_attribute_name(:name)
      %div= t Employee.human_attribute_name(:active)
      %div
    - @employees.each do |employee|
      %section.employee
        %div= employee.name
        %div= employee.active
        %div.btns
          = link_to 'Show', employee
          = link_to 'Edit', edit_employee_path(employee)
          = link_to 'Mark Inactive', employee, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/employees/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @employee.first_name
%p
  %b Last name:
  = @employee.last_name
%p
  %b Active:
  = @employee.active

= link_to 'Edit', edit_employee_path(@employee)
\|
= link_to 'Back', employees_path