config/routes.rb
ESPPep::Application.routes.draw do

  resources :cards, path: "/", only: [ :new, :create, :show ]
  devise_for :users, path: "/admin"

  scope :admin do
    resources :cards, except: [ :new, :create, :show ]
    resources :clubs
    resources :users
    resources :employees, except: [ :new ]
  end

  root to: 'cards#new'

  

end

app/models/card.rb
class Card < ActiveRecord::Base
  VALUES = {
    en: ["Excellence","Teamwork","Service","Talent","Courage","Integrity","Flexibility","Accountability","Respect","Performance","Community","Fun"],
    es: ["Excelencia","Trabajo En Equipo","Servicio","Talento","Valor","Integridad","Flexibilidad","Responsabilidad","Respeto","Rendimiento","Comunidad","Divertido"]
  }
  SERVICESTANDARDS = {
    en: ["Smile & Greet","Use Names","Product Knowledge","Grooming Standards","Safety & Cleanliness","Anticipate Needs","Create Moments of Truth","Resolve Issues & Follow Up","Thank You","Teamwork & Cooperation","Privacy & Security","Be a Club Ambassador"],
    es: ["Sonría Y Salude","Usar Nombres","El Conocimiento Del Producto","Normas De Aseo Personal","Seguridad Y Limpieza","Anticipar Las Necesidades","Crear Momentos De La Verdad","Resolver Problemas Y Seguimiento","Gracias"," Trabajo En Equipo Y Cooperación"," Privacidad Y Seguridad"," Sé Un Embajador Club"]
  }
  has_one :club
  belongs_to :employee, ->(card) { where name: card.name }
  validates :name, :from_name, :club_id, :value, :service_standard, :note, presence: true
  validates_associated :club
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [ :new, :create ]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @card }
      else
        format.html { render action: 'new' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:from_name, :name, :position, :club_id, :manager_name, :value, :service_standard, :note, :from_email, :email)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.haml
= form_for @card do |f|
  = render(partial: "shared/errors", locals: { object: @card }) if @card.errors.any?

  %label
    %strong= Card.human_attribute_name(:from_name).titleize
    = f.text_field :from_name, placeholder: Card.human_attribute_name(:from_name).titleize, placeholder: Card.human_attribute_name(:from_name).titleize
  %label
    %strong= Card.human_attribute_name(:from_email).titleize
    = f.text_field :from_email, placeholder: Card.human_attribute_name(:from_email).titleize
  %label
    %strong= Card.human_attribute_name(:name).titleize
    = f.text_field :name, placeholder: Card.human_attribute_name(:name).titleize
  %label
    %strong= Card.human_attribute_name(:email).titleize
    = f.text_field :email, placeholder: Card.human_attribute_name(:email).titleize
  %label
    %strong= Card.human_attribute_name(:position).titleize
    = f.text_field :position, placeholder: Card.human_attribute_name(:position).titleize
  %label
    %strong= Card.human_attribute_name(:club_id).titleize
    = f.select :club_id, Club.order('name ASC').map{|c| [c.name, c.id]}, include_blank: "–#{Card.human_attribute_name(:club).titleize}–"
  %label
    %strong= Card.human_attribute_name(:manager_name).titleize
    = f.text_field :manager_name, placeholder: Card.human_attribute_name(:manager_name).titleize
  %label
    %strong= Card.human_attribute_name(:value).titleize
    = f.select :value, Card::VALUES[I18n.locale].each_with_index.map{|k,v| [ k, v] }, include_blank: "–#{Card.human_attribute_name(:value).titleize}–"
  %label
    %strong= Card.human_attribute_name(:service_standard).titleize
    = f.select :service_standard, Card::SERVICESTANDARDS[I18n.locale].each_with_index.map{|k,v| [ k, v] }, include_blank: "–#{Card.human_attribute_name(:service_standard).titleize}–"
  %label
    %strong= Card.human_attribute_name(:note).titleize
    = f.text_area :note, placeholder: Card.human_attribute_name(:note).titleize
  .actions
    = f.submit 'Save'

app/views/cards/edit.html.haml
- content_for :title, "Editing #{ link_to "Card", @card }".html_safe

= render 'form'

app/views/cards/index.html.haml
- content_for :title, t("listing_cards")


- if @cards.empty?
  %section#cards.empty= t('none', model: Card.model_name.human)
- else
  %section#cards.table
    %header
      %div= Card.human_attribute_name(:name).titleize
      %div= Card.human_attribute_name(:position).titleize
      %div= Card.human_attribute_name(:club).titleize
      %div= Card.human_attribute_name(:manager_name).titleize
      %div= Card.human_attribute_name(:value).titleize
      %div= Card.human_attribute_name(:service_standard).titleize
      %div= Card.human_attribute_name(:from_name).titleize
      %div= Card.human_attribute_name(:from_email).titleize
      %div
    - @cards.each do |card|
      %section.card
        %div
          - if card.email
            = link_to card.name, "mailto:#{card.email}"
          - else
            = card.name
        %div= card.position
        %div= card.club.short
        %div= card.manager_name
        %div= Card::VALUES[I18n.locale][card.value]
        %div= Card::SERVICE_STANDARDS[I18n.locale][card.service_standard]
        %div= card.from_name
        %div= card.from_email
        %div.btns
          = link_to 'Show', card
          = link_to 'Edit', edit_card_path(card)
          = link_to 'Destroy', card, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/cards/new.html.haml
- content_for :title, t("new", model: Card.model_name.human)

= render 'form'

app/views/cards/show.html.haml
%p#notice= notice

%p
  %b From name:
  = @card.from_name
%p
  %b Name:
  = @card.name
%p
  %b Position:
  = @card.position
%p
  %b Club:
  = @card.club_id
%p
  %b Manager name:
  = @card.manager_name
%p
  %b Value:
  = @card.value
%p
  %b Service standard:
  = @card.service_standard
%p
  %b Note:
  = @card.note
%p
  %b From email:
  = @card.from_email

= link_to 'Edit', edit_card_path(@card)
\|
= link_to 'Back', cards_path